# 1º: Utilizando a última versão da imagem node como imagem base
FROM node:19-alpine3.15

# 2º: Definir o diretório de trabalho
WORKDIR /usr/src/app

# Copiar package.json (do DockerHost) no diretorio de trabalho
COPY package.json .